# Generated by Django 5.0.4 on 2024-07-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_studentenrollment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='main_app.subject'),
        ),
    ]
