# Generated by Django 5.1.1 on 2024-10-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_comment_options_and_more'),
        ('pets', '0002_alter_pet_slug'),
        ('photos', '0002_alter_photos_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
    ]
