# Generated by Django 5.0.4 on 2024-06-28 20:02

from django.db import migrations


def set_group(apps, schema_editor):
    single_person = apps.get_model('main_app', 'Person')

    people = single_person.objects.all()

    for person in people:
        if person.age <= 12:
            person.age_group = 'Child'
        elif person.age <= 17:
            person.age_group = 'Teen'
        else:
            person.age_group = 'Adult'

    single_person.objects.bulk_update(people, ['age_group'])


def set_group_default(apps, schema_editor):
    single_person = apps.get_model('main_app', 'Person')

    people = single_person.objects.all()

    for person in people:
        person.age_group = single_person._meta.get_field('age_group').default
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_person'),
    ]

    operations = [
        migrations.RunPython(set_group, set_group_default)
    ]
