# Generated by Django 5.1.2 on 2024-10-27 10:27

import FurryFunnies.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='passcode',
            field=models.CharField(max_length=6, validators=[FurryFunnies.utils.validators.validate_passcode]),
        ),
    ]
