# Generated by Django 5.1.2 on 2024-10-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_alter_post_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_at']},
        ),
    ]
